In [1]:
from scipy.stats import geom

In [3]:
geom.ppf(0.5,0.5)

1.0

In [4]:
geom.pmf(3,0.5)

0.125

In [6]:
rv=geom(0.5)

In [7]:
rv.pmf(1)

0.5

In [8]:
geom.rvs(0.4,size=100)

array([6, 6, 1, 2, 1, 1, 3, 6, 6, 5, 1, 2, 6, 2, 1, 1, 5, 1, 2, 1, 4, 1,
       4, 2, 1, 2, 1, 6, 1, 2, 6, 1, 2, 4, 1, 1, 1, 2, 1, 1, 1, 3, 3, 1,
       1, 4, 1, 2, 7, 4, 4, 3, 4, 4, 3, 4, 2, 1, 3, 3, 1, 2, 1, 1, 4, 5,
       1, 5, 3, 2, 3, 1, 4, 4, 2, 2, 5, 1, 1, 2, 2, 1, 1, 3, 3, 2, 3, 1,
       1, 1, 2, 3, 1, 1, 2, 1, 3, 2, 2, 1])

In [9]:
import numpy as np

In [13]:
 x1 = np.linspace(0, 10, 11, endpoint=True)

In [14]:
x1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
from scipy.stats import binom

In [16]:
binom.pmf(1,10,0.5)

0.00976562500000001

In [17]:
binom.ppf(0.1,10,0.5)

3.0

In [18]:
binom.rvs(10,.5,size=100)

array([2, 4, 4, 5, 5, 6, 3, 7, 3, 8, 3, 6, 6, 4, 7, 6, 8, 5, 8, 3, 4, 3,
       6, 2, 5, 7, 4, 6, 7, 5, 4, 7, 4, 5, 3, 4, 6, 4, 6, 6, 4, 4, 6, 5,
       4, 4, 8, 5, 7, 6, 6, 3, 4, 7, 5, 4, 6, 4, 2, 3, 7, 6, 7, 5, 5, 5,
       4, 4, 7, 5, 6, 7, 8, 7, 7, 6, 3, 2, 5, 5, 8, 5, 3, 6, 6, 5, 7, 6,
       7, 5, 1, 6, 6, 4, 2, 0, 4, 4, 5, 7])